name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -c conda-forge pytest ruff xraylib
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Lint with Ruff
      run: |
        ruff --output-format=github .
        continue-on-error: true
    - name: Test with pytest
      run: |
        pytest
